version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: django_project
    command: ["./wait-for-it/wait-for-it.sh", "db:5432", "-s", "-t", "60", "--strict", "--",
     "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    volumes:
      - ./django_project:/code
    expose:
      - "8000"
    ports:
      - 8000:8000
    depends_on:
      - db
