version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: django_project
   command: ["./wait-for-it/wait-for-it.sh", "db:5432", "-s", "-t", "60", "--strict", "--",
   "gunicorn", "project.wsgi", "-b", "0.0.0.0:8000"]
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=db
    volumes:
      - ./django_project:/code
    expose:
      - "8000"
    ports:
      - 8000:8000
    depends_on:
      - db

  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/certs/etc:/etc/letsencrypt
      - ./certbot/certs/data:/data/letsencrypt
      - ./django_project:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  cert:
    build: certbot
    volumes:
      - ./certbot/certs/etc:/etc/letsencrypt
      - ./certbot/certs/data:/data/letsencrypt
    depends_on:
      - server
    command: echo "ran"

